# -*- coding: utf-8 -*-
"""Alexnet

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OhhDUb43Vy-Nr2LaIykdxp03DA8jg79N
"""

import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout, BatchNormalization
from tensorflow.keras.initializers import HeNormal

class AlexNet(tf.keras.Model):
    def __init__(self, input_shape=(224, 224, 3), num_classes=1000, dropout_rate=0.5):
        super(AlexNet, self).__init__()
        initializer = HeNormal()

        self.model = Sequential([
            # 1st Convolutional Layer
            Conv2D(96, (11, 11), strides=4, padding='valid', activation='relu',
                   kernel_initializer=initializer, input_shape=input_shape),
            BatchNormalization(),
            MaxPooling2D(pool_size=(3, 3), strides=2, padding='valid'),

            # 2nd Convolutional Layer
            Conv2D(256, (5, 5), padding='same', activation='relu', kernel_initializer=initializer),
            BatchNormalization(),
            MaxPooling2D(pool_size=(3, 3), strides=2, padding='valid'),

            # 3rd, 4th, 5th Convolutional Layers
            Conv2D(384, (3, 3), padding='same', activation='relu', kernel_initializer=initializer),
            Conv2D(384, (3, 3), padding='same', activation='relu', kernel_initializer=initializer),
            Conv2D(256, (3, 3), padding='same', activation='relu', kernel_initializer=initializer),
            MaxPooling2D(pool_size=(3, 3), strides=2, padding='valid'),

            # Flatten + Fully Connected Layers
            Flatten(),
            Dense(4096, activation='relu', kernel_initializer=initializer),
            Dropout(dropout_rate),
            Dense(4096, activation='relu', kernel_initializer=initializer),
            Dropout(dropout_rate),
            Dense(num_classes, activation='softmax')
        ])

    def call(self, inputs):
        return self.model(inputs)

# Example usage
if __name__ == "__main__":
    input_shape = (128, 128, 3)  # smaller dataset example
    num_classes = 10             # e.g., CIFAR-10
    dropout_rate = 0.4

    model = AlexNet(input_shape=input_shape, num_classes=num_classes, dropout_rate=dropout_rate)
    model.build((None, *input_shape))
    model.summary()