# -*- coding: utf-8 -*-
"""LSTM

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zZyJMGXJJGgrp4jv9cQx-JuJsfD5fCTq
"""

# -*- coding: utf-8 -*-
"""
Enhanced LSTM Forecasting Model
Auto-runs with Airline Passengers Dataset from URL
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from keras.models import Sequential
from keras.layers import Dense, LSTM, Dropout
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error
import math
import warnings
warnings.filterwarnings("ignore")

# ---------------------------------------------------------
# 1️⃣ LOAD DATASET DIRECTLY FROM URL
# ---------------------------------------------------------
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/airline-passengers.csv"
data = pd.read_csv(url)
print("✅ Dataset Loaded Successfully from GitHub")
print(data.head())

# Convert Month to datetime for better time plots
data['Month'] = pd.to_datetime(data['Month'])
plt.figure(figsize=(10,4))
plt.plot(data['Month'], data['Passengers'], color='navy')
plt.title("International Airline Passengers Over Time")
plt.xlabel("Year")
plt.ylabel("Number of Passengers")
plt.grid(True)
plt.show()

# ---------------------------------------------------------
# 2️⃣ DATA PREPARATION
# ---------------------------------------------------------
dataset = data["Passengers"].values.astype("float32").reshape(-1, 1)

# Normalize data
scaler = MinMaxScaler(feature_range=(0, 1))
dataset = scaler.fit_transform(dataset)

# Split into train/test (75/25)
train_size = int(len(dataset) * 0.75)
train, test = dataset[:train_size], dataset[train_size:]

# Create sequence samples
def create_dataset(data, time_step=10):
    X, Y = [], []
    for i in range(len(data) - time_step):
        X.append(data[i:(i + time_step), 0])
        Y.append(data[i + time_step, 0])
    return np.array(X), np.array(Y)

time_step = 10
trainX, trainY = create_dataset(train, time_step)
testX, testY = create_dataset(test, time_step)

# Reshape to (samples, time_steps, features)
trainX = trainX.reshape(trainX.shape[0], time_step, 1)
testX = testX.reshape(testX.shape[0], time_step, 1)

# ---------------------------------------------------------
# 3️⃣ MODEL CREATION (Improved)
# ---------------------------------------------------------
model = Sequential([
    LSTM(16, return_sequences=True, input_shape=(time_step, 1)),  # more neurons
    Dropout(0.2),
    LSTM(8, return_sequences=False),
    Dense(1)
])

model.compile(optimizer='adam', loss='mse')
model.summary()

# ---------------------------------------------------------
# 4️⃣ TRAINING
# ---------------------------------------------------------
history = model.fit(trainX, trainY, epochs=40, batch_size=8, verbose=1)

# Plot loss curve
plt.figure(figsize=(8,4))
plt.plot(history.history['loss'], color='purple')
plt.title("Training Loss Over Epochs")
plt.xlabel("Epochs")
plt.ylabel("Loss (MSE)")
plt.grid(True)
plt.show()

# ---------------------------------------------------------
# 5️⃣ PREDICTIONS
# ---------------------------------------------------------
trainPredict = model.predict(trainX)
testPredict = model.predict(testX)

# Inverse transform
trainPredict = scaler.inverse_transform(trainPredict)
testPredict = scaler.inverse_transform(testPredict)
trainY_inv = scaler.inverse_transform(trainY.reshape(-1, 1))
testY_inv = scaler.inverse_transform(testY.reshape(-1, 1))

# RMSE evaluation
train_rmse = math.sqrt(mean_squared_error(trainY_inv, trainPredict))
test_rmse = math.sqrt(mean_squared_error(testY_inv, testPredict))

print(f"\n📊 Model Performance:")
print(f"Train RMSE: {train_rmse:.2f}")
print(f"Test RMSE:  {test_rmse:.2f}")

# ---------------------------------------------------------
# 6️⃣ VISUALIZATION
# ---------------------------------------------------------
trainPlot = np.empty_like(dataset)
trainPlot[:] = np.nan
trainPlot[time_step:len(trainPredict)+time_step] = trainPredict

testPlot = np.empty_like(dataset)
testPlot[:] = np.nan
testPlot[len(trainPredict)+(time_step*2):len(dataset)] = testPredict

plt.figure(figsize=(10,6))
plt.plot(scaler.inverse_transform(dataset), label='Actual Data', color='blue')
plt.plot(trainPlot, label='Train Predictions', color='green')
plt.plot(testPlot, label='Test Predictions', color='red')
plt.title("✈️ International Airline Passenger Forecasting (Enhanced LSTM)")
plt.xlabel("Time Steps")
plt.ylabel("Passengers")
plt.legend()
plt.grid(True)
plt.show()

# ---------------------------------------------------------
# 7️⃣ FUTURE FORECASTING (Next 12 months)
# ---------------------------------------------------------
last_sequence = dataset[-time_step:]  # last 10 values
predictions = []

for _ in range(12):
    pred_input = last_sequence.reshape(1, time_step, 1)
    next_val = model.predict(pred_input)
    predictions.append(next_val[0,0])
    last_sequence = np.append(last_sequence[1:], next_val)[-time_step:]

# Convert back to original scale
future_forecast = scaler.inverse_transform(np.array(predictions).reshape(-1, 1))

# Display future results
print("\n🔮 Predicted Next 12 Months Passenger Counts:")
print(np.round(future_forecast.flatten(), 1))

# Plot future forecast
plt.figure(figsize=(10,5))
plt.plot(scaler.inverse_transform(dataset), label="Actual Data", color="blue")
future_x = np.arange(len(dataset), len(dataset) + 12)
plt.plot(future_x, future_forecast, 'o--', label="Future Forecast (Next 12 Months)", color="orange")
plt.title("Future Passenger Forecasting")
plt.xlabel("Time Steps")
plt.ylabel("Passengers")
plt.legend()
plt.grid(True)
plt.show()