# -*- coding: utf-8 -*-
"""mask/withoutmask

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mU50FxcUd1GTnI0C4JIRDhC1jI9Kcp_g
"""

# --- STEP 1: Download GitHub Dataset ---
!wget https://github.com/chandrikadeb7/Face-Mask-Detection/archive/refs/heads/master.zip -O mask_dataset.zip
!unzip -q mask_dataset.zip

dataset_dir = "Face-Mask-Detection-master/dataset"

# --- STEP 2: Imports ---
import tensorflow as tf
import os
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras import layers, models
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from google.colab import files

# --- STEP 3: Data Generators (with Augmentation) ---
train_datagen = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2,
    rotation_range=25,
    width_shift_range=0.25,
    height_shift_range=0.25,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True,
    brightness_range=[0.8,1.2]
)

val_datagen = ImageDataGenerator(rescale=1./255, validation_split=0.2)

train_generator = train_datagen.flow_from_directory(
    dataset_dir,
    target_size=(150,150),
    batch_size=32,
    class_mode='binary',
    subset="training"
)

val_generator = val_datagen.flow_from_directory(
    dataset_dir,
    target_size=(150,150),
    batch_size=32,
    class_mode='binary',
    subset="validation"
)

# --- STEP 4: Base Model (MobileNetV2) ---
base_model = tf.keras.applications.MobileNetV2(
    input_shape=(150,150,3),
    include_top=False,
    weights="imagenet"
)

base_model.trainable = False  # freeze first for transfer learning

# --- STEP 5: Build Model ---
model = models.Sequential([
    layers.RandomFlip("horizontal"),
    layers.RandomRotation(0.1),
    layers.RandomZoom(0.1),
    base_model,
    layers.GlobalAveragePooling2D(),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.4),
    layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# --- STEP 6: Train Initial Model ---
history = model.fit(
    train_generator,
    validation_data=val_generator,
    epochs=10,
    verbose=2
)

# --- STEP 7: Fine-Tune Top Layers ---
base_model.trainable = True  # unfreeze base model
# Optional: freeze lower layers, fine-tune only top
for layer in base_model.layers[:-40]:
    layer.trainable = False

model.compile(optimizer=tf.keras.optimizers.Adam(1e-5),
              loss='binary_crossentropy',
              metrics=['accuracy'])

history_fine = model.fit(
    train_generator,
    validation_data=val_generator,
    epochs=15,   # more training after fine-tuning
    verbose=2
)

# --- STEP 8: Plot Results ---
def plot_history(history1, history2):
    acc = history1.history['accuracy'] + history2.history['accuracy']
    val_acc = history1.history['val_accuracy'] + history2.history['val_accuracy']
    loss = history1.history['loss'] + history2.history['loss']
    val_loss = history1.history['val_loss'] + history2.history['val_loss']
    epochs = range(len(acc))

    plt.figure(figsize=(12,5))
    plt.subplot(1,2,1)
    plt.plot(epochs, acc, label='Train Acc')
    plt.plot(epochs, val_acc, label='Val Acc')
    plt.legend(); plt.title("Accuracy")

    plt.subplot(1,2,2)
    plt.plot(epochs, loss, label='Train Loss')
    plt.plot(epochs, val_loss, label='Val Loss')
    plt.legend(); plt.title("Loss")
    plt.show()

plot_history(history, history_fine)

# --- STEP 9: Test on Your Own Image ---
uploaded = files.upload()
for fn in uploaded.keys():
    img = tf.keras.preprocessing.image.load_img(fn, target_size=(150, 150))
    x = tf.keras.preprocessing.image.img_to_array(img)
    x = np.expand_dims(x, axis=0) / 255.0
    pred = model.predict(x)[0][0]
    label = "Without Mask ❌" if pred > 0.5 else "With Mask ✅"
    print(f"{fn} → {label} (confidence: {pred:.2f})")