# -*- coding: utf-8 -*-
"""RNN

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f1AdrVUcuxB1Pe0bXhP5I6OgbmOPpwLy
"""

# -- coding: utf-8 --
"""
Created on Tue Oct 28 13:53:48 2025
Modified on Dec 13 2025
@author: USER

Improved RNN Character-Level Text Generator
"""

import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Dense
import random

# -------------------------------------------------------------
# 1️⃣ Input text data
# -------------------------------------------------------------
text = "The beautiful girl whom I met last time is very intelligent also"
# text = "The handsome boy whom I met last time is very intelligent also"

# Unique characters and mapping dictionaries
chars = sorted(list(set(text)))
char_to_index = {char: i for i, char in enumerate(chars)}
index_to_char = {i: char for i, char in enumerate(chars)}

# -------------------------------------------------------------
# 2️⃣ Prepare sequences for training
# -------------------------------------------------------------
seq_length = 6  # slightly longer context improves accuracy
sequences = []
labels = []

for i in range(len(text) - seq_length):
    seq = text[i:i + seq_length]
    label = text[i + seq_length]
    sequences.append([char_to_index[c] for c in seq])
    labels.append(char_to_index[label])

X = np.array(sequences)
y = np.array(labels)

# One-hot encoding
X_one_hot = tf.one_hot(X, len(chars))
y_one_hot = tf.one_hot(y, len(chars))

# -------------------------------------------------------------
# 3️⃣ Build RNN Model
# -------------------------------------------------------------
model = Sequential([
    SimpleRNN(128, input_shape=(seq_length, len(chars)), activation='tanh'),
    Dense(len(chars), activation='softmax')
])

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.summary()

# -------------------------------------------------------------
# 4️⃣ Train the model
# -------------------------------------------------------------
model.fit(X_one_hot, y_one_hot, epochs=200, verbose=1)

# -------------------------------------------------------------
# 5️⃣ Generate new text
# -------------------------------------------------------------
def generate_text(model, start_seq, gen_length=80):
    generated = start_seq
    for _ in range(gen_length):
        # Prepare input: last seq_length characters
        input_seq = generated[-seq_length:]
        x = np.array([[char_to_index[c] for c in input_seq]])
        x_one_hot = tf.one_hot(x, len(chars))

        # Predict next character
        prediction = model.predict(x_one_hot, verbose=0)[0]

        # Add randomness for variety
        next_index = np.random.choice(len(chars), p=prediction)
        next_char = index_to_char[next_index]
        generated += next_char
    return generated

# -------------------------------------------------------------
# 6️⃣ Try both sequences
# -------------------------------------------------------------
start_seq_1 = "The beautiful girl whom I met "
start_seq_2 = "The handsome boy whom I met "

print("\nGenerated Text (girl version):")
print(generate_text(model, start_seq_1))

print("\nGenerated Text (boy version):")
print(generate_text(model, start_seq_2))