# -*- coding: utf-8 -*-
"""TicTacToe

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eh2ikSkm3_eFi2RxoyolzRUQwBre8SMc
"""

# -*- coding: utf-8 -*-
"""
Tic Tac Toe - Reinforcement Learning
"""

import numpy as np
import pickle

BOARD_ROWS = 3
BOARD_COLS = 3


class State:
    def __init__(self, p1, p2):
        self.board = np.zeros((BOARD_ROWS, BOARD_COLS))
        self.p1 = p1
        self.p2 = p2
        self.isEnd = False
        self.boardHash = None
        # player 1 always starts first
        self.playerSymbol = 1

    def getHash(self):
        """Get a unique hash of the current board."""
        self.boardHash = str(self.board.reshape(BOARD_COLS * BOARD_ROWS))
        return self.boardHash

    def winner(self):
        """Check the winner or tie."""
        # Check rows
        for i in range(BOARD_ROWS):
            if sum(self.board[i, :]) == 3:
                self.isEnd = True
                return 1
            if sum(self.board[i, :]) == -3:
                self.isEnd = True
                return -1

        # Check columns
        for i in range(BOARD_COLS):
            if sum(self.board[:, i]) == 3:
                self.isEnd = True
                return 1
            if sum(self.board[:, i]) == -3:
                self.isEnd = True
                return -1

        # Check diagonals
        diag_sum1 = sum([self.board[i, i] for i in range(BOARD_COLS)])
        diag_sum2 = sum([self.board[i, BOARD_COLS - i - 1] for i in range(BOARD_COLS)])
        if abs(diag_sum1) == 3 or abs(diag_sum2) == 3:
            self.isEnd = True
            return 1 if diag_sum1 == 3 or diag_sum2 == 3 else -1

        # Tie condition
        if len(self.availablePositions()) == 0:
            self.isEnd = True
            return 0

        # Game not ended
        self.isEnd = False
        return None

    def availablePositions(self):
        """Return a list of all empty positions."""
        positions = []
        for i in range(BOARD_ROWS):
            for j in range(BOARD_COLS):
                if self.board[i, j] == 0:
                    positions.append((i, j))
        return positions

    def updateState(self, position):
        """Make a move on the board."""
        self.board[position] = self.playerSymbol
        # Switch player
        self.playerSymbol = -1 if self.playerSymbol == 1 else 1

    def giveReward(self):
        """Give rewards to both players based on the result."""
        result = self.winner()
        if result == 1:
            self.p1.feedReward(1)
            self.p2.feedReward(0)
        elif result == -1:
            self.p1.feedReward(0)
            self.p2.feedReward(1)
        else:
            # Draw
            self.p1.feedReward(0.5)
            self.p2.feedReward(0.5)

    def reset(self):
        """Reset the board for a new game."""
        self.board = np.zeros((BOARD_ROWS, BOARD_COLS))
        self.boardHash = None
        self.isEnd = False
        self.playerSymbol = 1

    def play(self, rounds=10000):
        """Train both agents through self-play."""
        for i in range(rounds):
            while not self.isEnd:
                # Player 1
                positions = self.availablePositions()
                p1_action = self.p1.chooseAction(positions, self.board, self.playerSymbol)
                self.updateState(p1_action)
                board_hash = self.getHash()
                self.p1.addState(board_hash)

                win = self.winner()
                if win is not None:
                    self.giveReward()
                    self.p1.reset()
                    self.p2.reset()
                    self.reset()
                    break

                # Player 2
                positions = self.availablePositions()
                p2_action = self.p2.chooseAction(positions, self.board, self.playerSymbol)
                self.updateState(p2_action)
                board_hash = self.getHash()
                self.p2.addState(board_hash)

                win = self.winner()
                if win is not None:
                    self.giveReward()
                    self.p1.reset()
                    self.p2.reset()
                    self.reset()
                    break

            if i % 1000 == 0:
                print(f"Training round: {i}")

    def play2(self):
        """Play against a human."""
        while not self.isEnd:
            # Computer move
            positions = self.availablePositions()
            p1_action = self.p1.chooseAction(positions, self.board, self.playerSymbol)
            self.updateState(p1_action)
            self.showBoard()

            win = self.winner()
            if win is not None:
                if win == 1:
                    print(f"{self.p1.name} wins!")
                else:
                    print("It's a tie!")
                self.reset()
                break

            # Human move
            positions = self.availablePositions()
            p2_action = self.p2.chooseAction(positions)
            self.updateState(p2_action)
            self.showBoard()

            win = self.winner()
            if win is not None:
                if win == -1:
                    print(f"{self.p2.name} wins!")
                else:
                    print("It's a tie!")
                self.reset()
                break

    def showBoard(self):
        """Display the board."""
        for i in range(BOARD_ROWS):
            print('-------------')
            out = '| '
            for j in range(BOARD_COLS):
                token = ' '
                if self.board[i, j] == 1:
                    token = 'X'
                elif self.board[i, j] == -1:
                    token = 'O'
                out += token + ' | '
            print(out)
        print('-------------')


class Player:
    def __init__(self, name, exp_rate=0.3):
        self.name = name
        self.states = []
        self.lr = 0.2
        self.exp_rate = exp_rate
        self.decay_gamma = 0.9
        self.states_value = {}

    def getHash(self, board):
        return str(board.reshape(BOARD_COLS * BOARD_ROWS))

    def chooseAction(self, positions, current_board, symbol):
        """Choose action based on epsilon-greedy strategy."""
        if np.random.uniform(0, 1) <= self.exp_rate:
            # Explore
            idx = np.random.choice(len(positions))
            action = positions[idx]
        else:
            # Exploit
            value_max = -999
            for p in positions:
                next_board = current_board.copy()
                next_board[p] = symbol
                next_boardHash = self.getHash(next_board)
                value = self.states_value.get(next_boardHash, 0)
                if value >= value_max:
                    value_max = value
                    action = p
        return action

    def addState(self, state):
        self.states.append(state)

    def feedReward(self, reward):
        """Update state values using reward backpropagation."""
        for st in reversed(self.states):
            if self.states_value.get(st) is None:
                self.states_value[st] = 0
            self.states_value[st] += self.lr * (self.decay_gamma * reward - self.states_value[st])
            reward = self.states_value[st]

    def reset(self):
        self.states = []

    def savePolicy(self):
        with open('policy_' + str(self.name), 'wb') as fw:
            pickle.dump(self.states_value, fw)

    def loadPolicy(self, file):
        with open(file, 'rb') as fr:
            self.states_value = pickle.load(fr)


class HumanPlayer:
    def __init__(self, name):
        self.name = name

    def chooseAction(self, positions):
        """Get human move."""
        while True:
            row = int(input("Enter your move row (0-2): "))
            col = int(input("Enter your move col (0-2): "))
            action = (row, col)
            if action in positions:
                return action
            else:
                print("Invalid move, try again.")


if __name__ == "__main__":
    print("Training the agent...")
    p1 = Player("p1")
    p2 = Player("p2")

    st = State(p1, p2)
    st.play(50000)

    # Save learned policy
    p1.savePolicy()
    p2.savePolicy()

    # Play with human
    print("\nGame start!")
    p1 = Player("computer", exp_rate=0)
    p1.loadPolicy("policy_p1")
    p2 = HumanPlayer("human")

    st = State(p1, p2)

    while True:
        st.play2()
        choice = input("Play again? (y/n): ").lower()
        if choice != 'y':
            break